"""Remove klaussy's scaffolding from a repo.

klaussy writes three different kinds of thing, and undoing each one safely means
treating it differently:

1. Files it fully owns — skill directories, guard scripts, generated ignore
   files. These are deleted outright, but only when something positively marks
   them as klaussy's: a `.klaussy-version` marker, the `klaussy_` script prefix,
   or the `# klaussy:` header the generated ignore files carry.
2. Files it *shares* — `.gitignore` and each agent's settings/config, which
   klaussy merges into and which usually hold the user's own entries too. These
   are edited, never deleted.
3. Conventions docs (`CLAUDE.md`, `GEMINI.md`, `AGENTS.md`, `CONVENTIONS.md`).
   klaussy generates them, but people hand-edit them and they are the expensive
   thing to recreate, so they survive unless `include_conventions` is set.

Anything that doesn't carry an ownership marker is reported rather than removed.
A repo that had its own `.cursorignore` before klaussy ran keeps it.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from klaussy.agents import BACKENDS
from klaussy.agents.backends import SECRET_IGNORE_MARKER
from klaussy.gitignore import GITIGNORE_ENTRIES
from klaussy.settings import SENSITIVE_PATTERNS
from klaussy.skills import SKILL_NAMES, VERSION_FILE, sanitize_skill_namespace

# Guard scripts in Claude's own hooks directory. Every other agent gets the
# `klaussy_` prefix, which is enough on its own.
CLAUDE_GUARDS = (
    "read_injection_guard.py",
    "git_commit_guard.py",
    "comment_guard.py",
    "dependency_guard.py",
    "plan_guidance.py",
    "self_review_guard.py",
)
GUARD_PREFIX = "klaussy_"

# Directories klaussy creates wholesale for a single agent.
OWNED_DIRS = (
    ".claude/rules",
    ".claude/hooks",
    ".cursor/rules",
    ".cursor/hooks",
    ".codex/hooks",
    ".gemini/hooks",
    ".opencode/rules",
    ".opencode/plugins",
    ".clinerules",
    ".github/hooks",
    ".github/instructions",
    ".kimi-code",
    ".gemini/antigravity-cli",
    ".conventions",
)

# Generated ignore files, deleted only when the klaussy header is present.
IGNORE_FILES = (".cursorignore", ".geminiignore", ".clineignore", ".aiderignore")

# Conventions docs — kept unless include_conventions.
CONVENTIONS_FILES = (
    "CLAUDE.md",
    "GEMINI.md",
    "AGENTS.md",
    "CONVENTIONS.md",
    ".antigravityrules",
    ".aider.conf.yml",
    ".github/copilot-instructions.md",
)
# Path-scoped conventions klaussy drops into source subdirectories.
NESTED_CONVENTIONS = ("AGENTS.md", "GEMINI.md")

# Settings files klaussy merges hook entries into. Never deleted.
SHARED_CONFIGS = (
    ".claude/settings.json",
    ".gemini/settings.json",
    ".cursor/hooks.json",
    ".codex/hooks.json",
    ".agents/settings.json",
)

# Keys that carry no content of their own. A config left holding only these
# after the klaussy entries come out existed solely to hold them.
VESTIGIAL_KEYS = frozenset({"version", "$schema"})

# Configs klaussy generates whole, with no hook signature to key off. Deleted
# only when every top-level key is one klaussy writes — a user key means theirs.
# Files klaussy writes whole and stamps. Deleted only when the stamp is there,
# so a hand-written config of the same name survives.
GENERATED_HEADER = "Generated by klaussy"
HEADER_OWNED = (".codex/config.toml",)

GENERATED_CONFIGS = {
    ".cursor/permissions.json": frozenset({"terminalAllowlist", "mcpAllowlist"}),
    ".agents/settings.json": frozenset({"terminal"}),
    "opencode.json": frozenset({"$schema", "instructions", "provider", "permission"}),
}

# A hook entry is klaussy's when its command mentions one of these.
HOOK_SIGNATURES = ("klaussy-hook", "klaussy_", "klaussy humanize")


@dataclass(frozen=True)
class Removal:
    """A path to delete, and why we believe it is klaussy's."""

    path: str
    is_dir: bool
    reason: str


@dataclass(frozen=True)
class Edit:
    """A shared file to rewrite rather than delete."""

    path: str
    reason: str


@dataclass
class UninstallPlan:
    """What an uninstall would do, before it does any of it."""

    repo: Path
    removals: list[Removal] = field(default_factory=list)
    edits: list[Edit] = field(default_factory=list)
    kept: list[tuple[str, str]] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        return not self.removals and not self.edits


def _rel(repo: Path, path: Path) -> str:
    return path.relative_to(repo).as_posix()


def _skill_dirs(repo: Path) -> list[Path]:
    """Every scaffolded skill directory, across all agents."""
    namespace = sanitize_skill_namespace(repo.name)
    roots = {".claude/skills"}
    for backend in BACKENDS.values():
        profile = getattr(backend, "profile", None)
        root = getattr(profile, "skills_root", None)
        if root:
            roots.add(root)

    found: list[Path] = []
    for root in sorted(roots):
        root_dir = repo / root
        if not root_dir.is_dir():
            continue
        for skill in SKILL_NAMES:
            candidate = root_dir / f"{namespace}-{skill}"
            if candidate.is_dir():
                found.append(candidate)
        marker = root_dir / VERSION_FILE
        if marker.is_file():
            found.append(marker)
    return found


def _guard_scripts(repo: Path) -> list[Path]:
    """Guard scripts, identified by name rather than by location."""
    found: list[Path] = []
    for name in CLAUDE_GUARDS:
        candidate = repo / ".claude" / "hooks" / name
        if candidate.is_file():
            found.append(candidate)
    for path in sorted(repo.rglob(f"{GUARD_PREFIX}*.py")):
        if ".git/" not in path.as_posix():
            found.append(path)
    return found


def _nested_conventions(repo: Path) -> list[Path]:
    """Path-scoped AGENTS.md / GEMINI.md klaussy writes into subdirectories.

    Only files below the repo root count: the root copies are handled with the
    other conventions docs, and a nested one is only ever klaussy's.
    """
    found: list[Path] = []
    for name in NESTED_CONVENTIONS:
        for path in sorted(repo.rglob(name)):
            rel = path.relative_to(repo)
            if len(rel.parts) == 1:
                continue
            if any(part == ".git" or part.startswith(".") for part in rel.parts[:-1]):
                continue
            found.append(path)
    return found


def _without_secret_block(text: str) -> str:
    """The ignore file minus klaussy's marked block, leaving user entries."""
    block = {SECRET_IGNORE_MARKER, *SENSITIVE_PATTERNS}
    return "\n".join(ln for ln in text.splitlines() if ln.strip() not in block)


def _is_vestigial(data: object) -> bool:
    """True when nothing of substance is left after the klaussy entries come out."""
    return isinstance(data, dict) and set(data) <= VESTIGIAL_KEYS


def _klaussy_hook_entries(value: object) -> bool:
    """True when a settings fragment mentions a klaussy guard anywhere inside."""
    return any(sig in json.dumps(value) for sig in HOOK_SIGNATURES)


def plan(repo: Path, *, include_conventions: bool = False) -> UninstallPlan:
    """Work out what to remove without touching anything."""
    repo = Path(repo).resolve()
    result = UninstallPlan(repo=repo)
    seen: set[str] = set()

    def add_removal(path: Path, reason: str) -> None:
        rel = _rel(repo, path)
        if rel in seen:
            return
        seen.add(rel)
        result.removals.append(Removal(path=rel, is_dir=path.is_dir(), reason=reason))

    for path in _skill_dirs(repo):
        add_removal(path, "scaffolded skill")
    for path in _guard_scripts(repo):
        add_removal(path, "klaussy guard script")

    for rel in OWNED_DIRS:
        path = repo / rel
        if path.is_dir():
            add_removal(path, "klaussy-owned directory")

    for rel in IGNORE_FILES:
        path = repo / rel
        if not path.is_file():
            continue
        text = path.read_text(errors="replace")
        if SECRET_IGNORE_MARKER not in text:
            result.kept.append((rel, "no klaussy block — entirely hand-written"))
        elif _without_secret_block(text).strip():
            result.edits.append(Edit(path=rel, reason="drop klaussy's secret block"))
        else:
            add_removal(path, "ignore file holding only klaussy's block")

    if include_conventions:
        for rel in CONVENTIONS_FILES:
            path = repo / rel
            if path.is_file():
                add_removal(path, "conventions doc (--all)")
        for path in _nested_conventions(repo):
            add_removal(path, "path-scoped conventions (--all)")
    else:
        present = [r for r in CONVENTIONS_FILES if (repo / r).is_file()]
        if present:
            result.kept.append(
                (", ".join(present), "conventions docs are kept; pass --all to remove them")
            )

    gitignore = repo / ".gitignore"
    if gitignore.is_file():
        content = gitignore.read_text(errors="replace")
        if any(entry in content for entry in GITIGNORE_ENTRIES):
            result.edits.append(Edit(path=".gitignore", reason="drop klaussy's entries"))

    for rel in HEADER_OWNED:
        path = repo / rel
        if not path.is_file():
            continue
        head = "\n".join(path.read_text(errors="replace").splitlines()[:3])
        if GENERATED_HEADER in head:
            add_removal(path, "klaussy-generated config")
        else:
            result.kept.append((rel, "no klaussy header — looks hand-written"))

    for rel, owned_keys in GENERATED_CONFIGS.items():
        path = repo / rel
        if not path.is_file():
            continue
        try:
            keys = set(json.loads(path.read_text()))
        except (json.JSONDecodeError, ValueError, TypeError):
            result.kept.append((rel, "unparseable JSON — left for you to edit"))
            continue
        if keys <= owned_keys:
            add_removal(path, "klaussy-generated config")
        else:
            result.kept.append((rel, "holds keys klaussy does not write — left alone"))

    for rel in SHARED_CONFIGS:
        path = repo / rel
        if not path.is_file():
            continue
        if rel.endswith(".json"):
            try:
                data = json.loads(path.read_text())
            except (json.JSONDecodeError, ValueError):
                result.kept.append((rel, "unparseable JSON — left for you to edit"))
                continue
            if _klaussy_hook_entries(data):
                if _is_vestigial(_prune(data)):
                    add_removal(path, "config existed only for klaussy's entries")
                else:
                    result.edits.append(Edit(path=rel, reason="remove klaussy hook entries"))
        else:
            text = path.read_text(errors="replace")
            if any(sig in text for sig in HOOK_SIGNATURES):
                result.kept.append((rel, "klaussy entries present — remove them by hand"))

    return result


def _strip_gitignore(path: Path) -> None:
    lines = path.read_text().splitlines()
    kept = [ln for ln in lines if ln.strip() not in GITIGNORE_ENTRIES]
    while kept and not kept[-1].strip():
        kept.pop()
    path.write_text("\n".join(kept) + "\n" if kept else "")


def _prune(value: object) -> object:
    """Drop klaussy hook entries from a settings fragment, keeping the rest."""
    if isinstance(value, list):
        pruned = [_prune(v) for v in value if not _klaussy_hook_entries(v)]
        return [v for v in pruned if v not in ({}, [])]
    if isinstance(value, dict):
        out = {}
        for key, val in value.items():
            if _klaussy_hook_entries(val) and not isinstance(val, (dict, list)):
                continue
            new = _prune(val) if isinstance(val, (dict, list)) else val
            if new in ({}, []) and isinstance(val, (dict, list)):
                continue
            out[key] = new
        return out
    return value


def _strip_settings(path: Path) -> None:
    data = json.loads(path.read_text())
    path.write_text(json.dumps(_prune(data), indent=2) + "\n")


def _prune_empty_dirs(repo: Path) -> list[str]:
    """Remove directories klaussy emptied, deepest first. Never the repo root."""
    removed: list[str] = []
    candidates = {
        ".claude",
        ".cursor",
        ".codex",
        ".gemini",
        ".agents",
        ".github",
        ".opencode",
        ".kimi-code",
    }
    for rel in sorted(candidates, key=len, reverse=True):
        path = repo / rel
        if not path.is_dir():
            continue
        for sub in sorted(path.rglob("*"), key=lambda p: -len(p.parts)):
            if sub.is_dir() and not any(sub.iterdir()):
                sub.rmdir()
        if not any(path.iterdir()):
            path.rmdir()
            removed.append(rel)
    return removed


def apply(plan_: UninstallPlan) -> UninstallPlan:
    """Carry out a plan. Returns it, with pruned directories folded in."""
    import shutil

    repo = plan_.repo
    for removal in plan_.removals:
        path = repo / removal.path
        if removal.is_dir:
            shutil.rmtree(path, ignore_errors=True)
        else:
            path.unlink(missing_ok=True)

    for edit in plan_.edits:
        path = repo / edit.path
        if not path.is_file():
            continue
        if edit.path == ".gitignore":
            _strip_gitignore(path)
        elif edit.path in IGNORE_FILES:
            cleaned = _without_secret_block(path.read_text()).rstrip()
            path.write_text(cleaned + "\n" if cleaned else "")
        else:
            _strip_settings(path)

    for rel in _prune_empty_dirs(repo):
        plan_.removals.append(Removal(path=rel, is_dir=True, reason="emptied by the uninstall"))
    return plan_
